unbind C-b
set -g prefix ";"

unbind r
bind r source-file ~/.tmux.conf \; display "Reloaded ~/.tmux.conf"

set -g mouse on
set-option -g mouse on
set-option -sg escape-time 10
set-option -g focus-events on

set -sg terminal-overrides ",*:RGB"

set -g history-limit 100000

unbind n  # DEFAULT KEY: Move to next window
unbind w  # DEFAULT KEY: change current window interactively

bind n command-prompt "rename-window '%%'"
bind w new-window -c "#{pane_current_path}"

set -g base-index 1
set-window-option -g pane-base-index 1

set-window-option -g mode-keys vi

# theme
set -g pane-border-style fg='#757581'
set -g pane-active-border-style fg='#e29eca'
set -g message-style bg='#252525',fg='#ea83a5'
set -g status-style bg='#252525',fg='#aca1cf'
set -g status-interval 1
set -g status-right '#[fg=#8be9fd,bg=#252525] #(tmux-mem-cpu-load -g 5 --interval 2) '
set -ga status-right '#[fg=#ff79c6,bg=#252525] #(uptime | cut -f 4-5 -d " " | cut -f 1 -d ",") '
set -ga status-right '#[fg=#bd93f9,bg=#252525] %a %H:%M:%S'

### copy & paste -------------------------------------------------------
# Use vim keybindings in copy mode
setw -g mode-keys vi
# Setup 'v' to begin selection as in Vim
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"
# Update default binding of `Enter` to also use copy-pipe
unbind -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"
