"use strict";var r=Object.defineProperty;var d=Object.getOwnPropertyDescriptor;var i=Object.getOwnPropertyNames;var l=Object.prototype.hasOwnProperty;var u=(e,a)=>{for(var t in a)r(e,t,{get:a[t],enumerable:!0})},g=(e,a,t,p)=>{if(a&&typeof a=="object"||typeof a=="function")for(let s of i(a))!l.call(e,s)&&s!==t&&r(e,s,{get:()=>a[s],enumerable:!(p=d(a,s))||p.enumerable});return e};var C=e=>g(r({},"__esModule",{value:!0}),e);var A={};u(A,{default:()=>m});module.exports=C(A);var o=require("@raycast/api"),n=require("@raycast/api");var f=[{Name:"Arcana Pack",Appearance:"arcana.png",Cost:"$4",Effect:"Choose 1 of up to 3 Tarot cards to be used immediately"},{Name:"Jumbo Arcana Pack",Appearance:"arcana_jumbo.png",Cost:"$6",Effect:"Choose 1 of up to 5 Tarot cards to be used immediately"},{Name:"Mega Arcana Pack",Appearance:"arcana_mega.png",Cost:"$8",Effect:"Choose 2 of up to 5 Tarot cards to be used immediately"},{Name:"Celestial Pack",Appearance:"celestial.png",Cost:"$4",Effect:"Choose 1 of up to 3 Planet cards to be used immediately"},{Name:"Jumbo Celestial Pack",Appearance:"celestial_jumbo.png",Cost:"$6",Effect:"Choose 1 of up to 5 Planet cards to be used immediately"},{Name:"Mega Celestial Pack",Appearance:"celestial_mega.png",Cost:"$8",Effect:"Choose 2 of up to 5 Planet cards to be used immediately"},{Name:"Standard Pack",Appearance:"standard.png",Cost:"$4",Effect:"Choose 1 of up to 3 Playing cards to add to your deck"},{Name:"Jumbo Standard Pack",Appearance:"standard_jumbo.png",Cost:"$6",Effect:"Choose 1 of up to 5 Playing cards to add to your deck"},{Name:"Mega Standard Pack",Appearance:"standard_mega.png",Cost:"$8",Effect:"Choose 2 of up to 5 Playing cards to add to your deck"},{Name:"Buffoon Pack",Appearance:"buffoon.png",Cost:"$4",Effect:"Choose 1 of up to 2 Joker cards"},{Name:"Jumbo Buffoon Pack",Appearance:"buffoon_jumbo.png",Cost:"$6",Effect:"Choose 1 of up to 4 Joker cards"},{Name:"Mega Buffoon Pack",Appearance:"buffoon_mega.png",Cost:"$8",Effect:"Choose 2 of up to 4 Joker cards"},{Name:"Spectral Pack",Appearance:"spectral.png",Cost:"$4",Effect:"Choose 1 of up to 2 Spectral cards to be used immediately"},{Name:"Jumbo Spectral Pack",Appearance:"spectral_jumbo.png",Cost:"$6",Effect:"Choose 1 of up to 4 Spectral cards to be used immediately"},{Name:"Mega Spectral Pack",Appearance:"spectral_mega.png",Cost:"$8",Effect:"Choose 2 of up to 4 Spectral cards to be used immediately"}];var c=require("react/jsx-runtime");function m(){return(0,c.jsx)(o.List,{isLoading:!0,isShowingDetail:!0,navigationTitle:"Boosters",searchBarPlaceholder:"Searching by Booster's name...",children:f.map((e,a)=>(0,c.jsx)(o.List.Item,{title:e.Name,detail:(0,c.jsx)(o.List.Item.Detail,{markdown:k(e)}),actions:(0,c.jsx)(o.ActionPanel,{children:(0,c.jsx)(o.Action,{title:"Cost",icon:o.Icon.Coins,onAction:()=>{let t=e.Cost;(0,n.showToast)({title:"Cost",message:t,style:n.Toast.Style.Success})}})})},a))})}function k(e){return`
# ${e.Name}

 ![](boosters/${e.Appearance})




## Effect
${e.Effect}
`}
